### ISSUE TITLE
release版本无法使用

### ISSUE THREAD

**Issue by sup817ch** [AcademicDog/onmyoji_bot#2]
```
2019-06-21 11:45:16,452 root        : INFO     python version: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)]
2019-06-21 11:45:16,452 root        : INFO     UAC pass

选择游戏模式(Ctrl-C跳过并单刷)：
0-单刷
1-本地双开
2-组队司机
3-组队打手
0

是否点怪？
0-不点怪
1-点中间怪
2-点右边怪
0

结束后如何处理？
0-退出
1-关机
0
2019-06-21 11:45:26,582 root        : INFO     Mode = 0
2019-06-21 11:45:26,582 root        : INFO     Emyc = 0
2019-06-21 11:45:26,592 root        : INFO     Postoperation = 0
2019-06-21 11:45:26,592 root        : INFO     registration successful
2019-06-21 11:45:26,592 root        : INFO     Activation successful
Traceback (most recent call last):
  File "onmyoji.py", line 92, in <module>
  File "onmyoji.py", line 67, in yuhun
  File "single_fight.py", line 21, in start
  File "game_ctl.py", line 236, in wait_game_img
  File "game_ctl.py", line 136, in find_img
cv2.error: OpenCV(4.1.0) C:\projects\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:589: error: (-215:Assertion failed) corrsize.height <= img.rows + templ.rows - 1 && corrsize.width <= img.cols + templ.cols - 1 in function 'cv::crossCorr'

[9964] Failed to execute script onmyoji
```
建议打包成多文件的那种试试，单文件的好像容易出错。

直接使用run.bat可以使用。

**Comment by AcademicDog** [comment]
这是因为程序打包到了单文件，但是并没有包含运行所依赖的/img/*文件，因此.exe文件应该和/img文件夹放在同一目录才能运行。目前已更新打包文件。
