### ISSUE TITLE
自动探索是否有问题？

### ISSUE THREAD

**Issue by sirodeneko** [AcademicDog/onmyoji_bot#35]
激活窗口成功
 Traceback (most recent call last):
   File "ui.py", line 125, in start_onmyoji
   File "explore\explore.py", line 19, in __init__
   File "configparser.py", line 828, in getboolean
   File "configparser.py", line 808, in _get_conv
   File "configparser.py", line 802, in _get
   File "configparser.py", line 791, in get
 NoOptionError: No option 'fight_boss_enable' in section: 'explore'

**Comment by AcademicDog** [comment]
你这个是更新了程序，但还用着原来的conf.ini，删除conf.ini就可以了。
