### ISSUE TITLE
单刷业原火结束时出现错误

### ISSUE THREAD

**Issue by Liangheemden** [AcademicDog/onmyoji_bot#45]
Fri, 28 Feb 2020 21:27:45  onmyoji.py  [line:87]  ERROR   Traceback (most recent call last):
   File "onmyoji.py", line 101, in <module>
   File "onmyoji.py", line 64, in init
   File "mitama\single_fight.py", line 50, in start
   File "gameLib\fighter.py", line 91, in check_end
 UnboundLocalError: local variable 'myend' referenced before assignment

**Comment by AcademicDog** [comment]
你一把的时间是不是超过了100s？

**Comment by Liangheemden** [comment]
emmm 应该超过了 感谢大佬解答
