### ISSUE TITLE
双开识别两个窗口后直接闪退

### ISSUE THREAD

**Issue by pboymt** [AcademicDog/onmyoji_bot#50]
双开是用痒痒熊开的

报错内容如下：

```
Wed, 04 Mar 2020 19:13:34  onmyoji.py  [line:106]  INFO  python version: 3.7.4 (default, Aug  9 2019, 18:22:51) [MSC v.1915 32 bit (Intel)]
Wed, 04 Mar 2020 19:13:34  onmyoji.py  [line:113]  INFO  UAC pass
Wed, 04 Mar 2020 19:13:34  explore_dual.py  [line:34]  INFO  检测到两个窗口，窗口信息正常
Wed, 04 Mar 2020 19:13:35  logsystem.py  [line:22]  INFO  绑定窗口成功
Wed, 04 Mar 2020 19:13:35  logsystem.py  [line:22]  INFO  8456682
Wed, 04 Mar 2020 19:13:35  logsystem.py  [line:22]  INFO  激活窗口成功
Wed, 04 Mar 2020 19:13:35  explore_dual.py  [line:47]  INFO  发现乘客
Wed, 04 Mar 2020 19:13:35  onmyoji.py  [line:102]  ERROR   Traceback (most recent call last):
   File "onmyoji.py", line 116, in <module>
   File "onmyoji.py", line 79, in init
   File "explore\explore_dual.py", line 50, in start
 AttributeError: 'ExploreDual' object has no attribute 'driver'
```

**Comment by AcademicDog** [comment]
没有检测到司机，你看看你是不是在组队好，且进入了探索里面开的脚本。
