### ISSUE TITLE
运行ui.py没有生成conf.ini文件，且运行onmyoji.py时提示找不到指定模块

### ISSUE THREAD

**Issue by buerking** [AcademicDog/onmyoji_bot#64]
报错如下：
C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\python.exe D:/python/11111/onmyoji.py
Traceback (most recent call last):
  File "D:/python/11111/onmyoji.py", line 1, in <module>
    from explore.explore import ExploreFight
  File "D:\python\11111\explore\explore.py", line 1, in <module>
    from gameLib.fighter import Fighter
  File "D:\python\11111\gameLib\fighter.py", line 1, in <module>
    from gameLib.game_ctl import GameControl
  File "D:\python\11111\gameLib\game_ctl.py", line 1, in <module>
    from gameLib.image_proc import match_img_knn
  File "D:\python\11111\gameLib\image_proc.py", line 1, in <module>
    import cv2
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37-32\lib\site-packages\cv2\__init__.py", line 3, in <module>
    from .cv2 import *
ImportError: DLL load failed: 找不到指定的模块。

numpy
pywin32
opencv_python
Pillow
opencv_contrib_python==3.4.2.16
所有库均已安装。

谢谢作者。

**Comment by AcademicDog** [comment]
我印象中这个问题是因为opencv没装好的原因，我现在用anaconda，直接安装没有什么问题。
