### ISSUE TITLE
ui.exe 运行无效

### ISSUE THREAD

**Issue by Statgenius** [AcademicDog/onmyoji_bot#67]
在沙箱环境下，所有requirement所需包已下载，点开ui.exe，运行无论御魂，御灵还是探索，阴阳师都没有任何反应；阴阳师未处于最小化。
点击log查看error。 内容如下。
2020 Mar 21 16:19:46 onmyoji.py        [line:114] INFO    root      UAC pass
2020 Mar 21 16:19:46 onmyoji.py        [line:102] ERROR   root       Traceback (most recent call last):
   File "onmyoji.py", line 117, in <module>
   File "onmyoji.py", line 45, in init
   File "mitama\single_fight.py", line 13, in __init__
   File "gameLib\fighter.py", line 50, in __init__
   File "gameLib\game_ctl.py", line 30, in __init__
 error: (1400, 'GetWindowRect', 'Invalid window handle.')

谷歌后，怀疑是pywinauto的版本问题，将pywinauto降低版本至pywinauto==0.6.4，log内容依旧不变。阴阳师也没有任何反应。

谢谢帮助。

**Comment by AcademicDog** [comment]
沙盒会改变阴阳师窗口名，需要设置。具体请看doc.onmyojibot.com。

**Comment by Statgenius** [comment]
我昨天已经成功设置了，但是用完，今天就被违规警告了。现在我想，最好能有能把御灵，御魂，探索组合起来的代码。可以防止网易探测单一刷本的行为。    	    	
    	获取 Outlook for iOS      



On Sun, Mar 22, 2020 at 2:47 PM +0100, "AcademicDog" <notifications@github.com> wrote:
















沙盒会改变阴阳师窗口名，需要设置。具体请看doc.onmyojibot.com。

**Comment by AcademicDog** [comment]
我感觉不只是功能的问题，同样的函数，在模拟器和大漠插件上实现就要可靠得多。所以我现在开了个新坑，做在手机上运行的apk。

**Comment by Statgenius** [comment]
可惜我只是个做数据分析的，不然可以略尽绵薄之力。







在 2020-03-24 22:14:10，"AcademicDog" <notifications@github.com> 写道：

我感觉不只是功能的问题，同样的函数，在模拟器和大漠插件上实现就要可靠得多。所以我现在开了个新坑，做在手机上运行的apk。

**Comment by ballerwangbo** [comment]
希望作者能统计一下有多少人，用了哪些功能，用了多长时间。这样就会知道哪些地方除了问题。
