### ISSUE TITLE
关于双开的问题

### ISSUE THREAD

**Issue by XIII13** [AcademicDog/onmyoji_bot#75]
尝试使用双开功能（御魂和探索）点击开始之后core文件闪退，但是ui还在
log：
2020 Jun 05 11:42:04 onmyoji.py        [line:114] INFO    root      UAC pass
2020 Jun 05 11:42:04 dual.py           [line:34 ] INFO    root      检测到两个窗口，窗口信息正常
2020 Jun 05 11:42:05 fighter.py        [line:51 ] INFO    root      绑定窗口成功
2020 Jun 05 11:42:05 fighter.py        [line:52 ] INFO    root      13634628
2020 Jun 05 11:42:05 fighter.py        [line:56 ] INFO    root      激活窗口成功
2020 Jun 05 11:42:05 dual.py           [line:46 ] INFO    root      发现乘客
2020 Jun 05 11:42:05 onmyoji.py        [line:102] ERROR   root       Traceback (most recent call last):
   File "onmyoji.py", line 117, in <module>
   File "onmyoji.py", line 79, in init
   File "mitama\dual.py", line 49, in start
 AttributeError: 'DualFighter' object has no attribute 'driver'

**Comment by XIII13** [comment]
刚才读了一下已经closed的问题。大概明白问题出在哪里了，得从准备房间里点击开始要不然会因为找不到司机而闪退。
