### ISSUE TITLE
无效的窗口句柄。

### ISSUE THREAD

**Issue by fengzidk** [AcademicDog/onmyoji_bot#84]
沙盒下报无效句柄

2021 Feb 25 15:43:36 onmyoji.py        [line:114] INFO    root      UAC pass
2021 Feb 25 15:43:36 onmyoji.py        [line:102] ERROR   root       Traceback (most recent call last):
   File "onmyoji.py", line 117, in <module>
   File "onmyoji.py", line 68, in init
   File "explore\explore.py", line 18, in __init__
   File "gameLib\fighter.py", line 50, in __init__
   File "gameLib\game_ctl.py", line 30, in __init__
 error: (1400, 'GetWindowRect', '无效的窗口句柄。')

**Comment by fengzidk** [comment]
限制 - 降低权限 选项卡， 勾选 降低管理员和超级用户组的权限。
这个配置之后,直接无法启动客户端

**Comment by fengzidk** [comment]
外观 选项卡， 取消勾选 不要在窗口标题中显示Sandboxie标志。
反向操作后, **勾选** 不要在窗口标题中显示Sandboxie标志,正常运行
